"""
research/make_tone_yield_chart.py

Chart 07: change in Resolution tone vs the 10-year G-sec on decision day,
with the same test run on other Indian markets alongside. A historical
research chart: drawn once from the analysis inputs and published as a static
image to assets/rbi_research/, not regenerated by the automated pipeline.

Inputs
  data/rbi_sentinel.db                                    Resolution scores, rate decisions
  data/India 10-Year Bond Yield Historical Data(1).csv    daily 10y G-sec (Investing.com)
  local/rbi_sentinel/market_prices_daily.csv              Nifty, Bank Nifty, USD/INR, gold, India VIX (Yahoo Finance)

The two price files are third-party data and are kept out of the repository
(.git/info/exclude); only the chart they produce is published.

Run from the project root:  .venv/bin/python research/make_tone_yield_chart.py
"""
from __future__ import annotations

import re
import sqlite3
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.lines import Line2D

ROOT = Path(__file__).resolve().parents[1]
LOCAL_INPUTS = ROOT / "local" / "rbi_sentinel"
sys.path.insert(0, str(ROOT))

from rbi_sentinel.cleaners.policy_facts import extract_policy_facts  # noqa: E402
from style.economics_hub_style import EconStyle  # noqa: E402

OUT = ROOT / "assets" / "rbi_research" / "07_rbi_tone_vs_10y.png"
NAVY, RED, BLUE, GREY = "#003366", "#A61B29", "#1F4E79", "#9AA2AD"


# ── Data ──────────────────────────────────────────────────────────────────────
con = sqlite3.connect(ROOT / "data/rbi_sentinel.db")
res = pd.read_sql(
    """SELECT m.policy_cycle, m.rate_action, m.rate_change_bps, s.overall_score AS s_res, d.raw_text
       FROM mpc_meetings m
       JOIN rbi_documents d ON d.meeting_id = m.meeting_id AND d.doc_type = 'resolution'
       JOIN sentiment_scores s ON s.doc_id = d.doc_id AND s.scoring_model_version = 'hybrid_v2'
       WHERE m.meeting_date = m.policy_cycle
       ORDER BY m.policy_cycle""", con)
res["date"] = pd.to_datetime(res.policy_cycle)
res["bps"] = np.where(res.rate_action == "hold", 0.0, res.rate_change_bps.fillna(0).astype(float))


def stated_stance(text: str) -> float:
    """Ordinal stated stance: accommodative −1, neutral 0, tightening +1."""
    t = " ".join((text or "").split())
    s = extract_policy_facts(t)["stated_stance"]
    if s is None:
        m = re.search(r"consistent with (?:an?|the) (accommodative|neutral) stance|stance of (calibrated tightening)|"
                      r"maintain the (neutral|accommodative) (?:monetary policy )?stance|keep the (?:policy )?stance (neutral)",
                      t, re.I)
        s = next(x for x in m.groups() if x).lower() if m else None
    return {"accommodative": -1, "neutral": 0, "calibrated tightening": 1,
            "withdrawal of accommodation": 1}.get(s, np.nan)


res["stance"] = res.raw_text.map(stated_stance)
# Apr/May 2022 Resolutions: "remain accommodative while focusing on withdrawal of accommodation"
res.loc[res.policy_cycle.isin(["2022-04-08", "2022-05-04"]), "stance"] = 1
res["d_tone"] = res.s_res.diff()
res["d_stance"] = res.stance.diff().fillna(0)

g = pd.read_csv(ROOT / "data/India 10-Year Bond Yield Historical Data(1).csv", encoding="utf-8-sig")
g["Date"] = pd.to_datetime(g.Date, format="%d-%m-%Y")
y10 = g.set_index("Date").sort_index().Price.astype(float)
px = pd.read_csv(LOCAL_INPUTS / "market_prices_daily.csv", index_col=0, parse_dates=True)
px["gold_inr"] = px.gold_usd * px.usdinr
px = px.reindex(px.nifty.dropna().index).ffill()   # Indian trading calendar for every market


def day_move(series: pd.Series, d: pd.Timestamp, kind: str) -> float:
    s = series.dropna()
    i = s.index.searchsorted(d)
    if i < 1 or i >= len(s):
        return np.nan
    a, b = s.iloc[i - 1], s.iloc[i]
    return (b - a) * 100 if kind == "bps" else (b - a) if kind == "pts" else (np.log(b) - np.log(a)) * 100


res["y10"] = [day_move(y10, d, "bps") for d in res.date]
MARKETS = [("y10", "10-year G-sec yield"), ("nifty", "Nifty 50"), ("banknifty", "Bank Nifty"),
           ("usdinr", "USD/INR"), ("gold_inr", "Gold (₹)"), ("vix", "India VIX")]
for col, _ in MARKETS[1:]:
    res[col] = [day_move(px[col], d, "pts" if col == "vix" else "pct") for d in res.date]


# ── OLS with Newey–West (HAC, 1 lag) standard errors ────────────────────────
def ols_hac(y: np.ndarray, X: np.ndarray, lags: int = 1):
    X = np.column_stack([np.ones(len(X)), X])
    n, k = X.shape
    xtx_inv = np.linalg.inv(X.T @ X)
    beta = xtx_inv @ X.T @ y
    u = y - X @ beta
    xu = X * u[:, None]
    S = xu.T @ xu
    for L in range(1, lags + 1):
        w = 1 - L / (lags + 1)
        G = xu[L:].T @ xu[:-L]
        S += w * (G + G.T)
    cov = xtx_inv @ S @ xtx_inv                     # no small-sample scaling (statsmodels HAC default)
    return beta, np.sqrt(np.diag(cov)), 1 - (u @ u) / ((y - y.mean()) @ (y - y.mean()))


stats = {}
for col, label in MARKETS:
    d = res.dropna(subset=[col, "bps", "d_stance", "d_tone"])
    b, se, r2 = ols_hac(d[col].values, d[["bps", "d_stance", "d_tone"]].values)
    stats[col] = dict(label=label, beta=b[3], t=b[3] / se[3], n=len(d), r2=r2)
d10 = res.dropna(subset=["y10", "d_tone"])
b_simple = np.polyfit(d10.d_tone, d10.y10, 1)
sd_tone = d10.d_tone.std()
s10 = stats["y10"]
print(f"10y: beta={s10['beta']:+.2f} bps/unit  t={s10['t']:+.2f}  n={s10['n']}  R2={s10['r2']:.3f}  "
      f"typical shift sd={sd_tone:.2f} → {s10['beta'] * sd_tone:+.1f} bps;  simple slope {b_simple[0]:+.1f}")
for col, _ in MARKETS[1:]:
    print(f"{col:10s} t={stats[col]['t']:+.2f}")


# ── Chart ─────────────────────────────────────────────────────────────────────
EconStyle.apply_global_style()
fig = plt.figure(figsize=(12.5, 6.4))
fig.patch.set_facecolor(EconStyle.BACKGROUND)
gs = fig.add_gridspec(1, 2, width_ratios=[1.75, 1], wspace=0.30)
ax = fig.add_subplot(gs[0])
axb = fig.add_subplot(gs[1])

# Left: scatter
holds = d10[d10.bps == 0]
hikes = d10[d10.bps > 0]
cuts = d10[d10.bps < 0]
ax.axhline(0, color="#000000", lw=0.7, alpha=0.5, zorder=1)
ax.axvline(0, color="#000000", lw=0.7, alpha=0.5, zorder=1)
xs = np.linspace(d10.d_tone.min() - 0.05, d10.d_tone.max() + 0.05, 50)
ax.plot(xs, np.polyval(b_simple, xs), color=NAVY, lw=1.6, alpha=0.85, zorder=2)
ax.scatter(holds.d_tone, holds.y10, s=46, color=NAVY, alpha=0.85, edgecolor="white", lw=0.6, zorder=3)
ax.scatter(hikes.d_tone, hikes.y10, s=52, facecolor="white", edgecolor=RED, lw=1.6, zorder=3)
ax.scatter(cuts.d_tone, cuts.y10, s=52, facecolor="white", edgecolor=BLUE, lw=1.6, zorder=3)

ax.set_xlabel("Change in Resolution tone vs previous meeting  (−1 dovish … +1 hawkish scale)", fontsize=8.5)
ax.set_ylabel("10-year G-sec yield change on decision day (bps)", fontsize=8.5)
ax.tick_params(labelsize=8)
ax.yaxis.grid(True, color=EconStyle.GRID_COLOR, lw=0.5, alpha=0.6)
ax.xaxis.grid(False)
ax.set_ylim(min(-20, d10.y10.min() - 4), d10.y10.max() + 6)
ax.text(0.98, 0.04,
        f"+{s10['beta']:.1f} bps per unit of tone change  (t = {s10['t']:.1f})\n"
        f"≈ +{s10['beta'] * sd_tone:.0f} bps for a typical shift\n"
        f"controlling for the rate decision and any stance change",
        transform=ax.transAxes, va="bottom", ha="right", fontsize=7.8, color="#1A1A1A", linespacing=1.4,
        bbox=dict(boxstyle="round,pad=0.45", facecolor="white", edgecolor="#D6D6D6", lw=0.8))
ax.legend(handles=[
    Line2D([], [], marker="o", ls="", color=NAVY, markersize=6, label="Hold"),
    Line2D([], [], marker="o", ls="", markerfacecolor="white", markeredgecolor=RED, mew=1.5, markersize=6, label="Hike"),
    Line2D([], [], marker="o", ls="", markerfacecolor="white", markeredgecolor=BLUE, mew=1.5, markersize=6, label="Cut"),
], loc="upper left", fontsize=7.8, frameon=False, ncol=3, handletextpad=0.3, columnspacing=1.0)
ax.plot([0, 1], [1, 1], color=EconStyle.RULE_LIGHT, lw=0.8, transform=ax.transAxes, clip_on=False, zorder=10)

# Right: the same test across markets
order = [c for c, _ in MARKETS]
tvals = [stats[c]["t"] for c in order]
labels = [stats[c]["label"] for c in order]
ypos = np.arange(len(order))[::-1]
colors = [NAVY if abs(t) >= 1.96 else GREY for t in tvals]
axb.barh(ypos, tvals, color=colors, height=0.58, zorder=3)
for yp, t in zip(ypos, tvals):
    axb.text(t + (0.12 if t >= 0 else -0.12), yp, f"{t:+.1f}", va="center",
             ha="left" if t >= 0 else "right", fontsize=7.8, color="#1A1A1A")
axb.axvspan(-1.96, 1.96, color="#EEF1F5", zorder=1)
for x in (-1.96, 1.96):
    axb.axvline(x, color="#9AA2AD", lw=0.8, ls="--", zorder=2)
axb.axvline(0, color="#000000", lw=0.7, zorder=2)
axb.set_yticks(ypos)
axb.set_yticklabels(labels, fontsize=8.2)
lim = max(4.6, max(abs(t) for t in tvals) + 0.9)
axb.set_xlim(-lim, lim)
axb.set_xlabel("t-statistic on tone change (robust SEs)", fontsize=8.5)
axb.tick_params(axis="x", labelsize=8)
axb.xaxis.grid(False)
axb.yaxis.grid(False)
axb.text(0, -1.02, "not significant  (|t| < 1.96)", ha="center", va="bottom", fontsize=7, color="#6B7380")
axb.set_ylim(-1.15, len(order) - 0.4)
axb.plot([0, 1], [1, 1], color=EconStyle.RULE_LIGHT, lw=0.8, transform=axb.transAxes, clip_on=False, zorder=10)

# Panel headings and a figure-wide title, so the two titles cannot collide
ax.text(0.0, 1.03, "Decision-day move in the 10-year G-sec vs change in Resolution tone",
        transform=ax.transAxes, fontsize=9.5, fontweight="bold", va="bottom", ha="left")
axb.text(0.0, 1.03, "Same test on other markets", transform=axb.transAxes,
         fontsize=9.5, fontweight="bold", va="bottom", ha="left")
# House title block, as EconStyle.set_title + add_top_rule draw it on single-panel
# charts: bold title, subtitle directly beneath, heavy rule spanning the chart.
LEFT, RIGHT = 0.07, 0.97
fig.text(LEFT, 0.985, "Resolution Tone and the 10-Year G-Sec on Decision Day",
         fontproperties=EconStyle._get_font("bold"), fontsize=EconStyle.FONT_SIZE_TITLE,
         color=EconStyle.TEXT_TITLE, va="top", ha="left")
fig.text(LEFT, 0.937, "A more hawkish Resolution than the last lines up with higher bond yields that day; "
         "equities, the rupee and gold show no link",
         fontproperties=EconStyle._get_font("regular"), fontsize=EconStyle.FONT_SIZE_SUBTITLE,
         color=EconStyle.TEXT_SECONDARY, va="top", ha="left")
fig.add_artist(Line2D([LEFT, RIGHT], [0.898, 0.898], transform=fig.transFigure,
                      color=EconStyle.RULE_HEAVY, lw=1.5))

EconStyle.add_source(
    fig,
    f"RBI MPC Resolutions scored by RBI Sentinel; 10y G-sec: Investing.com; markets: Yahoo Finance · "
    f"{s10['n']} decisions, {d10.date.min():%b %Y} – {d10.date.max():%b %Y}",
)
fig.subplots_adjust(left=LEFT, right=RIGHT, top=0.83, bottom=0.12)
EconStyle.save_chart(fig, OUT)
print("saved", OUT)
